export const STATUS_CONFIG = {
  Pending: {
    bg: "bg-muted",
    light: "bg-muted",
    text: "text-muted-foreground",
    border: "border-border",
    gradient: "bg-muted-foreground",
    dot: "bg-muted-foreground",
  },
  Active: {
    bg: "bg-primary",
    light: "bg-primary/10",
    text: "text-primary",
    border: "border-primary/20",
    gradient: "bg-primary",
    dot: "bg-primary",
  },
  "On Hold": {
    bg: "bg-primary",
    light: "bg-primary/10",
    text: "text-primary",
    border: "border-primary/20",
    gradient: "bg-primary",
    dot: "bg-primary",
  },
  Completed: {
    bg: "bg-primary",
    light: "bg-primary/10",
    text: "text-primary",
    border: "border-primary/20",
    gradient: "bg-primary",
    dot: "bg-primary",
  },
  Cancelled: {
    bg: "bg-destructive",
    light: "bg-destructive/10",
    text: "text-destructive",
    border: "border-destructive/20",
    gradient: "bg-destructive",
    dot: "bg-destructive",
  },
};
